### ISSUE TITLE
Angular 9 Z-Index Not Working

### ISSUE THREAD

**Issue by hugoebarboza** [fetrarij/ngx-daterangepicker-material#266] opened 2020-04-22 17:11 UTC
Hi,

I have an app with Angular 9. I have a child ngx-daterangepicker-material component, but when I put the child component inside parent component, the ngx-daterangepicker didn't see correctly. I added the z-index 9999 property on matpicker class, but It doesn't work properly.

How can I fix it ?

Sincerely,
Hugo Barboza

**Comment by Timebutt** [comment] 2020-04-22 20:19
That's weird, you shouldn't have to set the `z-index` at all since we leverage the `@angular/cdk`. Are you using the latest version (3+) of the package?

**Comment by hugoebarboza** [comment] 2020-04-22 20:35
Hi, thanks for writing back.

Yes, I'm using the last version ("ngx-daterangepicker-material": "^3.0.1").

And following https://fetrarij.github.io/ngx-daterangepicker-material/simple

Best regards,
Hugo.

**Comment by Timebutt** [comment] 2020-04-22 20:38
There's not much for us to work with and help you here right? By default, the `.cdk-overlay-container` has a `z-index` of `1000`. I'm guessing there might be something on your page that has a `z-index` that is set higher than that. 

That, or you're maybe facing issues in your Angular application that prevent the picker from opening?

**Comment by hugoebarboza** [comment] 2020-04-22 23:25
Hi,

It's weird, because If I use DatePicker [Material](https://material.angular.io/components/datepicker/)  in my child component it's works well. 

I can open the ngx-daterangepicker-material from my child component. The issue is that I can't see  the ngx-datepicker properly.

Do you have any demo/stackblitz using ngx-datepicker as a child component ?

Sincerely,
Hugo.

**Comment by Timebutt** [comment] 2020-04-23 07:44
What do you mean when you say using `ngx-daterangepicker-material` as a child component? Can you provide a code example of what you are trying to do?

**Comment by aylmercarson** [comment] 2020-04-24 07:38
i had similar issue. it was resolved by making sure i was importing the correct css in the correct places. all is good now,

**Comment by justinwifit** [comment] 2020-05-13 16:46
I'm also seeing this issue when attempting to use the ngx-daterangepicker-material component inside of a material dialog on Angular 9. The component is transparent and when I select any of the dates it doesn't change visually.

**Comment by justinwifit** [comment] 2020-05-13 16:48
Here's a screenshot 
<img width="1037" alt="Screen Shot 2020-05-13 at 10 47 29 AM" src="https://user-images.githubusercontent.com/41127779/81841164-3ed9eb00-9507-11ea-96d0-29772a364902.png">

**Comment by hugoebarboza** [comment] 2020-05-13 16:50
That is the exactly my issue, I had to change to ngbDatepicker from ngbootstrap

**Comment by justinwifit** [comment] 2020-05-13 16:52
> That is the exactly my issue, I had to change to ngbDatepicker from ngbootstrap

Where would this change be made? I'm confused as to what you mean

**Comment by justinwifit** [comment] 2020-05-13 16:54
@hugoebarboza Are you saying you switched to a different package?

**Comment by hugoebarboza** [comment] 2020-05-13 16:58
Yes, I switched to a this [package]([url](https://ng-bootstrap.github.io/#/components/datepicker/examples))

**Comment by hugoebarboza** [comment] 2020-05-13 16:58
https://ng-bootstrap.github.io/#/components/datepicker/examples

**Comment by justinwifit** [comment] 2020-05-13 17:07
It looks like reverting to "ngx-daterangepicker-material": "^2.3.0" solved the issue for the most part. However, now I can't get the component to open in front of the dialog.
<img width="1035" alt="Screen Shot 2020-05-13 at 11 07 30 AM" src="https://user-images.githubusercontent.com/41127779/81842856-fb34b080-9509-11ea-9900-304fb6225cb8.png">

**Comment by hugoebarboza** [comment] 2020-05-13 17:13
You have to check css property

**Comment by Timebutt** [comment] 2020-05-13 20:40
Hi @justinwifit. Thanks for providing a screenshot to help me reproduce this issue. The problem here, is that the .scss theme for this component isn't loaded in your application. That theme is needed to make sure the component uses your current Angular Material theme and blends right into your application.

The current documentation or `ng add` command don't take this into account yet, which I just noticed when setting up a new project. I'll have a look at how other Material components solve this exactly.

To get this working in the current state of affairs (which I'm looking to elegantly address), you have to import the theme and use the mixin like so:

```
@import '~ngx-daterangepicker-material/daterangepicker-theme.scss';

// DateRangePicker theme
@include date-range-picker-theme($theme);
```

**Comment by devit** [comment] 2020-06-03 07:57
Hi, is there any update on this as I'm including one of the prebuilt themes
 @import "~@angular/material/prebuilt-themes/deeppurple-amber.css"; 

which is css so I can't import and include the date-range-picker-theme @mixin scss

Is there any working solution to including the  date-range-picker-theme with a pre-built material theme?

Thanks, for any suggestions.

**Comment by Timebutt** [comment] 2020-06-03 08:18
One of the things you can do to fix your problem meanwhile is to create `.scss` file, paste the above code in there and add that newly created `.scss` file to the `styles` array in your `angular.json`.

I haven't had time yet to investigate on how to use this without the custom theme, but it's clear it should be able to work stand-alone.

**Comment by devit** [comment] 2020-06-04 02:08
Hi, thanks for your suggestion, unfortunately this approach does not work with the prebuilt themes, 

Note: for anyone who just wants to temporarily brute force a fix for the prebuilt themes, just paste the below css into your component (s)css file and add ViewEncapsulation to your component.ts file
this css is for the angular/material/prebuilt-themes/deeppurple-amber.css theme.

.md-drppicker{background-color:#fff;color:rgba(0,0,0,.87)}.md-drppicker td.available:hover,.md-drppicker th.available:hover{background-color:rgba(0,0,0,.04);color:rgba(0,0,0,.87)}.md-drppicker td.off,.md-drppicker td.off.end-date,.md-drppicker td.off.in-range,.md-drppicker td.off.start-date{background-color:#fff;border-color:#fff;color:rgba(0,0,0,.38)}.md-drppicker td.in-range{background-color:#eee;border-color:#eee;color:rgba(0,0,0,.87)}.md-drppicker td.active{transition:background .3s ease-out,border .3s ease-out;background:rgba(0,0,0,.1)}.md-drppicker td.active,.md-drppicker td.active:hover{background-color:#673ab7;color:#fff}.md-drppicker .ranges ul li button{border-radius:4px;color:rgba(0,0,0,.87)}.md-drppicker .ranges ul li button.active{background-color:#673ab7;color:#fff}.md-drppicker .ranges ul li:hover{border-radius:4px;background-color:rgba(0,0,0,.04);color:#fff}

**Comment by dianramdhani** [comment] 2020-06-12 07:38
thanks @devit its work very well. just copy it to style.scss

**Comment by Timebutt** [comment] 2020-06-15 19:44
Hey @devit, do you think you could generate this css for all four prebuilt `Angular Material` themes?

- deeppurple-amber
- indigo-pink
- pink-bluegrey
- purple-green

I'll pick them up and bundle them in the package so that people can easily import the matching theme for the prebuilt theme they're already using, or use the custom theme solution that's already in place 👌

**Comment by devit** [comment] 2020-06-19 14:33
Here you go.

[theme-css.zip](https://github.com/fetrarij/ngx-daterangepicker-material/files/4805136/theme-css.zip)

**Closed** 2020-07-03 15:00 UTC

**Comment by abhishekPegusus** [comment] 2020-07-25 10:11
> It looks like reverting to "ngx-daterangepicker-material": "^2.3.0" solved the issue for the most part. However, now I can't get the component to open in front of the dialog.
> <img alt="Screen Shot 2020-05-13 at 11 07 30 AM" width="1035" src="https://user-images.githubusercontent.com/41127779/81842856-fb34b080-9509-11ea-9900-304fb6225cb8.png">

it works for me as well

**Comment by abhishekPegusus** [comment] 2020-07-25 10:11
good solution

**Comment by bhushangahire** [comment] 2021-06-14 18:53
Anyone got it working to bring it in front of the dialog?

**Comment by pantonis** [comment] 2024-03-28 07:14
> Anyone got it working to bring it in front of the dialog?

Did you manage to do it? Having the same issue

**Comment by pantonis** [comment] 2024-03-28 07:28
Actually I just managed to make it work

```
::ng-deep.md-drppicker {
    position: fixed!important;
    left: auto !important;
}
```
